py_kakeibo/login/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views

app_name = 'login'
# http://localhost:8000/login/~で表示するurlたち
urlpatterns = [
   # path('', views.login, name='login'),
   path("", auth_views.LoginView.as_view(template_name="login/login.vue"), name="login"),
   path('admin/', admin.site.urls),
   path('detail/', include('detail.urls')),
   path('index/', views.index, name='index'),
   path("logout/", auth_views.LogoutView.as_view(), name="logout"),
   path("signup/", views.signup, name="signup"),
]

py_kakeibo/py_kakeibo/urls.py
from django.contrib import admin
from django.urls import include, path

# 8000/ でアクセス
urlpatterns = [
    path('detail/', include('detail.urls')),
    path('login/', include('login.urls')),
    path('notification/', include('notification.urls')),
    path('admin/', admin.site.urls),
    # path('', include('kakeibo.urls')),
]

py_kakeibo/login/models.py
from django.db import models

# Create your models here.

py_kakeibo/login/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
# from .forms import SignupForm, LoginForm
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def signup(request):
    if request.method == "POST":
        form = UserCreationForm(request.POST)
        if form.is_valid():
            new_user = form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            # ユーザーを認証する
            new_user = authenticate(username=username, password=raw_password) 
            if new_user is not None:
                # ユーザーをログイン状態にする
                login(request, new_user)
                return redirect("notification:notification")
    else:
        form = UserCreationForm()
    return render(request, "login/signup.vue", {"form": form})

def login(request):
    cont = request.POST
    if request.method == 'POST':
        form = UserCreationForm(request.POST)
        if form.is_valid():
            user = form.get_user()
            if user:
                login(request, user)
                return redirect("notification:notification")
    else:
        # form = LoginForm()
        form = 0

    return render(request, 'login/login.vue', {"form": form, "cont": cont})

def index(request):
    return redirect("notification:notification")
    # return 

py_kakeibo/login/templates/login/login.html
 <!-- extends 'app/base.html'  -->
{% block content %}

<h2>ログイン</h2>
<form method="POST" action="{% url 'login:login' %}">
    {% csrf_token %}
    {% if form.errors %}
        <p>ユーザー名またはパスワードが間違っています。もう一度入力してください。</p>
    {% endif %}
    {% if request.user.is_authenticated %}
        <a href="{% url 'login:logout' %}">ログアウト</a>
    {% else %}
        <label>ユーザー名</label>
        <input name="username">
        <br>
        <label>パスワード</label>
        <input type="password" name="password">
        <br>
        <input type="submit" value="ログイン">
        <br>
        <a href="{% url 'login:signup' %}">ユーザー登録</a>
    {% endif %}
</form>

{% endblock %}

py_kakeibo/login/templates/login/signup.html
<!DOCTYPE html>
{% extends "common/base.html" %}
{% block title_block %}
    ユーザ登録
{% endblock %}

{% block script_block %}
<script>
    let id = 0
    
    export default {
      data() {
        return {
          newTodo: '',
          hideCompleted: false,
          todos: [
            { id: id++, text: 'Learn HTML', done: true },
            { id: id++, text: 'Learn JavaScript', done: true },
            { id: id++, text: 'Learn Vue', done: false }
          ]
        }
      },
      computed: {
        // ...
      },
      methods: {
        addTodo() {
          this.todos.push({ id: id++, text: this.newTodo, done: false })
          this.newTodo = ''
        },
        removeTodo(todo) {
          this.todos = this.todos.filter((t) => t !== todo)
        }
      }
    }
    </script>
{% endblock %}

{% block body_block %}
    <!-- <h1>Welcome</h1> -->
    <h2>ユーザー登録</h2>
    <form method="POST" action="{% url 'login:signup' %}">
        {% csrf_token %}
        <label>ユーザー名</label>
        {{ form.username }}
        {{ form.username.errors }}
        <br>
        <label>パスワード</label>
        {{ form.password1 }}
        {{ form.password1.errors }}
        <br>
        <label>パスワード(確認)</label>
        {{ form.password2 }}
        {{ form.password2.errors }}
        <br>
        <input type="submit" value="登録する">
    </form>
    
{% endblock %}