py_kakeibo/detail/urls.py
from django.urls import path

from . import views

app_name = 'detail'
# http://localhost:8000/kakeibo/~で表示するurlたち
urlpatterns = [
   # path('', views.index, name='index'),
   # ex: /kakeibo/5/
   # path('<int:date>/', views.detail_month, name='detail'),
   # path(''                                , views.detail_month    , name='detail'),
   path('index/'                          , views.index            , name='index'),
   path('<int:year>/<int:month>/edit/'    , views.edit             , name='regist'),
   path('<int:year>/<int:month>/'         , views.summary_month_y_m, name=''),
   path('<int:year>/'                     , views.summary_year_y   , name=''),
   path('summary_month/'                  , views.summary_month    , name='summary_month'),
   path('summary_year/'                   , views.summary_year     , name='summary_year'),
   path('<int:item_id>/item_edit/'        , views.item_edit        , name='item_edit'),
   # ex: /kakeibo/5/results/
   #  path('<int:question_id>/results/', views.results, name='results'),
   # ex: /kakeibo/5/vote/
   #  path('<int:question_id>/vote/', views.vote, name='vote'),
]

py_kakeibo/login/urls.py
from django.urls import path, include
from django.contrib import admin
from . import views
from django.contrib.auth import views as auth_views

app_name = 'login'
# http://localhost:8000/login/~で表示するurlたち
urlpatterns = [
   # path('', views.login, name='login'),
   path("", auth_views.LoginView.as_view(template_name="login/login.vue"), name="login"),
   path('admin/', admin.site.urls),
   path('detail/', include('detail.urls')),
   path('index/', views.index, name='index'),
   path("logout/", auth_views.LogoutView.as_view(), name="logout"),
   path("signup/", views.signup, name="signup"),
]

py_kakeibo/py_kakeibo/urls.py
from django.contrib import admin
from django.urls import include, path

# 8000/ でアクセス
urlpatterns = [
    path('detail/', include('detail.urls')),
    path('login/', include('login.urls')),
    path('notification/', include('notification.urls')),
    path('admin/', admin.site.urls),
    # path('', include('kakeibo.urls')),
]

py_kakeibo/detail/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    user_id = models.IntegerField(default=0)
    user_name = models.CharField(max_length=200)

class Item(models.Model):
    item_id = models.IntegerField(default=0)
    user_id = models.IntegerField(default=0)
    item_name = models.CharField(max_length=200)
    item_amount = models.IntegerField(default=0)
    item_memo = models.CharField(max_length=200)
    item_date = models.DateTimeField('date published')

class FixedItem(models.Model):
    # 固定費の項目
    
    fixed_item_id = models.IntegerField(default=0)
    user_id = models.IntegerField(default=0)
    fixed_item_name = models.CharField(max_length=200)
    fixed_item_amount = models.IntegerField(default=0)
    fixed_item_memo = models.CharField(max_length=200)

py_kakeibo/detail/views.py
from django.shortcuts import render
from .models import Item
from django.contrib.auth.decorators import login_required
from django import forms

from datetime import date

# Create your views here.
class ItemEditForm(forms.Form):
    # subject = forms.CharField(max_length=100)
    # message = forms.CharField(max_length=1000)
    # sender = forms.EmailField()

    item_date   = forms.CharField(max_length=100)
    item_amount = forms.CharField(max_length=100)
    item_name   = forms.CharField(max_length=100)
    item_memo   = forms.CharField(max_length=100)

@login_required
def index(request):
    latest_item_list = Item.objects.order_by('-item_date')[:5]
    context  = {'latest_item_list': latest_item_list}
    context |= {'user_name': request.user.username}
    return render(request, 'detail/index.vue', context)

# def detail_month(request, date):
@login_required
def detail_month(request):
    item = Item.objects.create(itam_id=0, user_id=0, item_name='スタバ', item_amount=2000, item_memo='新作', item_date='2023-02-05')
    # return render(request, 'detail/edit.vue', {'item': 'WRYYYYYYYYY!!!!!!'})
    context["item"] = item
    return render(request, 'detail/edit.vue', context)

@login_required
def edit(request, year, month): # , amount, memo, name
    submit = ""
    context = {}

    context["item"] = 'WRY.......'
    context["date"] = date.today()# 日付をpythonの標準ライブラリから取得
    if submit:
        template = 'detail/edit.vue'
        return render(request, template, context)

    template = 'detail/edit.vue'
    return render(request, template, context)

@login_required
def summary_month(request):
    d = date.today()
    year = d.year
    month = d.month
    return summary_month_y_m(request, year, month)

@login_required
def summary_month_y_m(request, year, month):

    item_list = Item.objects.get(id = 1)

    context = {}
    context["item_list"] = item_list
    context["user_name"] = request.user.username
    context["date"]      = date.today()# 日付をpythonの標準ライブラリから取得

    template = "detail/summary_month.vue"
    return render(request, template, context)

@login_required
def summary_year(request):
    d = date.today()
    year = d.year
    return summary_year_y(request, year)

@login_required
def summary_year_y(request, year):

    item_list = Item.objects.get(id = 1)

    context = {}
    context["item_list"] = item_list
    context["user_name"] = request.user.username
    context["date"]      = date.today()# 日付をpythonの標準ライブラリから取得

    template = "detail/summary_year.vue"
    return render(request, template, context)

@login_required
def item_edit(request, item_id):
    form = ItemEditForm(request.POST or None)
    if form.is_valid():
        # チェック
        item_date   = form.cleaned_data["item_date"]
        item_amount = form.cleaned_data["item_amount"]
        item_name   = form.cleaned_data["item_name"]
        item_memo   = form.cleaned_data["item_memo"]

        item = Item.objects.save(
            itam_id     = item_id, 
            user_id     = 0, # TODO ユーザID取得
            item_date   = item_date,
            item_amount = item_amount, 
            item_name   = item_name, 
            item_memo   = item_memo, 
        )

    item = Item.objects.get(id = item_id)
    initial_values = {
        'item_date'   : item.item_date,
        'item_amount' : item.item_amount, 
        'item_name'   : item.item_name, 
        'item_memo'   : item.item_memo, 
    }
    form = ItemEditForm(initial_values)
    
    action = '/detail/'+str(item_id)+"/item_edit/"

    context = {}
    context["item"]      = item
    context["action"]    = action
    context["user_name"] = request.user.username
    context["form"]      = form
    context["date"]      = date.today()# 日付をpythonの標準ライブラリから取得

    template = "detail/item_edit.vue"
    return render(request, template, context)

py_kakeibo/detail/templates/detail/detail_month.html
{{ item }}
<fieldset>
    <legend><h1>X月X日</h1></legend>
    <legend><h1>合計0円</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    <div>
        絞り込み:
        <select name="fillter">
            <option>選択肢のサンプル1</option>
            <option>選択肢のサンプル2</option>
            <option>選択肢のサンプル3</option>
        </select>
    </div>
    <div>
        並び順:
        <select name="sort">
            <option>選択肢のサンプル1</option>
            <option>選択肢のサンプル2</option>
            <option>選択肢のサンプル3</option>
        </select>
    </div>
    <div>
        <table border="1px">
            <tr><th>項目名</th><th>金額</th><th>備考</th><th>編集</th></tr>
            <tr><td>スタバ</td><td>2,000円</td><td>新作</td><td>[x]</td></tr>
            <tr><td>スタバ</td><td>2,000円</td><td>新作</td><td>[x]</td></tr>
        </table>
    </div>
    <!-- http://localhost:8000/kakeibo/2023/2/regist/　にアクセスする -->
    <form action="{% url 'detail:regist' 2023 2 %}" method="post">
        <!-- Djangoの機能　csrf対策 -->
        {% csrf_token %}
        <table border="1px">
            <tr><th>項目名</th><th>金額</th><th>備考</th></tr>
            <tr>
                <td><input id="" class="" type="text" value="項目名"></td>
                <td><input id="" class="" type="number" value="0"></td>
                <td><input id="" class="" type="text" value="備考"></td>
            </tr>
            <tr><td><input type="submit" value="regist"> </td></tr>
        </table>  
    </form>
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>

py_kakeibo/detail/templates/detail/index.html
{{user_name}}
{% if latest_item_list %}
    <ul>
    {% for item in latest_item_list %}
        <li><a href="/edit/{{ item.id }}/item_edit">{{ item.item_name }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No items are available.</p>
{% endif %}